modal_questions = {
    'lernen': {
        'subject': 'Wir',
        'help': 'haben',
        'body': 'die Vokabeln',
        'verb': 'lernen',
        'perfect': 'gelernt'},
    'arbeiten':{
        'subject': 'Ich',
        'help': 'habe',
        'body': 'den ganzen Tag hart',
        'verb': 'arbeiten',
        'perfect': 'gearbeitet'},
    'machen':{
        'subject': 'Ich',
        'help': 'habe',
        'body': 'keine Hausaufgaben',
        'verb':'machen',
        'perfect': 'gemacht'},
    'buchen':{
        'subject': 'Die Sekretärin',
        'help': 'hat',
        'body': 'ein Hotelzimmer',
        'verb':'buchen',
        'perfect': 'gebucht'},
    'lösen':{
        'subject': 'Hans',
        'help': 'hat',
        'body': 'das Computerproblem',
        'verb':'lösen',
        'perfect': 'gelöst'},
    'hören':{
        'subject': 'Wir',
        'help': 'haben',
        'body': 'im Konzert fantastische Musik',
        'verb':'hören',
        'perfect': 'gehört'},
    'parken':{
        'subject': 'Ich',
        'help': 'habe',
        'body': 'mein Auto im Parkverbot',
        'verb': 'parken',
        'perfect': 'geparkt'},
    'tanzen':{
        'subject': 'Frau und Herr Schmalz',
        'help': 'haben',
        'body': 'die ganze Nacht Walzer',
        'verb': 'tanzen',
        'perfect': 'getanzt'},
    'senden':{
        'subject': 'Herr Klein',
        'help': 'hat',
        'body': 'die E-Mail um 18.30 Uhr',
        'verb': 'senden',
        'perfect': 'gesendet'},
    'kaufen':{
        'subject': 'Der Chef',
        'help': 'hat',
        'body': 'für seine Frau Blumen',
        'verb': 'kaufen',
        'perfect': 'gekauft'},
    'führen':{
        'subject': 'Wir',
        'help': 'haben',
        'body': 'mit Susanne ein Gespräch',
        'verb': 'führen',
        'perfect': 'geführt'},
    'frühstücken': {
        'subject': 'Sie (pl)',
        'help': 'haben',
        'body': 'im Hotel',
        'verb': 'frühstücken',
        'perfect': 'gefrühstückt'},
    'whonen': {
        'subject': 'Anton',
        'help': 'hat',
        'body': 'in Frankfurt',
        'verb': 'whonen',
        'perfect': 'gewhont'},
    'löschen':{
        'subject': 'Ich',
        'help': 'habe',
        'body': 'die E-Mail gestern',
        'verb': 'löschen',
        'perfect': 'gelöscht'},
    'leben':{
        'subject': 'Klara',
        'help': 'hat',
        'body': 'drei Jahre in Spanien',
        'verb': 'leben',
        'perfect': 'gelebt'},
    'rauchen':{
        'subject': 'Marianne',
        'help': 'hat',
        'body': '20 Zigaretten am Tag',
        'verb': 'rauchen',
        'perfect': 'geraucht'},
    'kochen':{
        'subject': 'Martin',
        'help': 'hat',
        'body': 'zem Abendessen Spaghetti',
        'verb': 'kochen',
        'perfect': 'gekocht'},
    'bezahlen': {
        'subject': 'Herr Krause',
        'help': 'hat',
        'body': 'seine Rechnung nicht',
        'verb': 'bezahlen',
        'perfect': 'bezahlt'},
    'vereinbaren': {
        'subject': 'Ich',
        'help': 'habe',
        'body': 'einen Termin mit Frau Kümmel',
        'verb': 'vereinbaren',
        'perfect': 'vereinbart'},
    'bestellen': {
        'subject': 'Peter',
        'help': 'hat',
        'body': 'shone ein Bier',
        'verb': 'bestellen',
        'perfect': 'bestellt'},
    'übersetzen': {
        'subject': 'Maartin',
        'help': 'hat',
        'body': 'den Brief schon',
        'verb': 'übersetzen',
        'perfect': 'übersetzt'},
    'begrüßen': {
        'subject': 'Herr Feuerstein',
        'help': 'hat',
        'body': 'den Brief schon',
        'verb': 'begrüßen',
        'perfect': 'begrüßt'},
    'einschalten': {
        'subject': 'Herr Feuerstein',
        'help': 'hat',
        'body': 'den Brief schon',
        'verb': 'einschalten',
        'perfect': 'eingeschaltet'},
    'einkaufen': {
        'subject': 'Herr Feuerstein',
        'help': 'hat',
        'body': 'den Brief schon',
        'verb': 'einkaufen',
        'perfect': 'eingekauft'},
    'landen': {
        'subject': 'Ich',
        'help': 'bin',
        'body': 'um 15.00 Uhr',
        'verb': 'landen',
        'perfect': 'gelandet'},
    'kommen': {
        'subject': 'Wir',
        'help': 'sind',
        'body': 'um 15.00 Uhr',
        'verb': 'kommen',
        'perfect': 'gekommen'},
    'lesen': {
        'subject': 'Sie (si)',
        'help': 'hat',
        'body': 'Liebesromane',
        'verb': 'lesen',
        'perfect': 'gelesen'},
    'schreiben': {
        'subject': 'Ich',
        'help': 'habe',
        'body': 'heute shone 30 E-Mails',
        'verb': 'schreiben',
        'perfect': 'geschrieben'},
    'gehen': {
        'subject': 'Wir',
        'help': 'sind',
        'body': 'erst um 24.oo Uhr ins Bett',
        'verb': 'gehen',
        'perfect': 'gegangen'},
    'finden': {
        'subject': 'Du',
        'help': 'hast',
        'body': 'meinen Kugelshreiber',
        'verb': 'finden',
        'perfect': 'gefunden'},
    'beginnen': {
        'subject': 'Die Besprechung',
        'help': 'hat',
        'body': 'um 12.00 Uhr',
        'verb': 'beginnen',
        'perfect': 'begonnen'},
    'singen': {
        'subject': 'Der Chor',
        'help': 'hat',
        'body': 'schöne Lieder',
        'verb': 'singen',
        'perfect': 'gesungen'},
    'schlafen': {
        'subject': 'Du',
        'help': 'hast',
        'body': 'um 22.00 Uhr gestern',
        'verb': 'schlafen',
        'perfect': 'geshlafen'},
    'ankommen': {
        'subject': 'Paul',
        'help': 'hat',
        'body': 'um 14.00 Uhr auf dem Flughafen',
        'verb': 'ankommen',
        'perfect': 'angekommen'},
    'sehen': {
        'subject': 'Oma',
        'help': 'hat',
        'body': 'den Film schon zehnmal',
        'verb': 'sehen',
        'perfect': 'gesehen'},
    'ausgehen': {
        'subject': 'Er',
        'help': 'ist',
        'body': 'davon',
        'verb': 'ausgehen',
        'perfect': 'ausgegangen'},
    'ausscheiden': {
        'subject': 'Die Fußballmannschaft',
        'help': 'ist',
        'body': 'aus dem Wettkampf',
        'verb': 'ausscheiden',
        'perfect': 'ausgeschieden'},
    'bleiben': {
        'subject': 'Wir',
        'help': 'haben',
        'body': 'eine nacht',
        'verb': 'bleiben',
        'perfect': 'ausgeschieden'},
    'aufnehmen': {
        'subject': 'Deutschland',
        'help': 'hat',
        'body': 'viele Flüchtlinge',
        'verb': 'aufnehmen',
        'perfect': 'aufgenommen'},
    'anfangen': {
        'subject': 'Das Konzert',
        'help': 'hat',
        'body': 'um 20.15 Uhr',
        'verb': 'anfangen',
        'perfect': 'angefangen'},
    'wohnen': {
        'subject': 'Ich',
        'help': 'habe',
        'body': 'auch einmal in Hamburg',
        'verb': 'wohnen',
        'perfect': 'gewohnt'},
    'essen': {
        'subject': 'Er',
        'help': 'hat',
        'body': 'schon viel fremdes Brot',
        'verb': 'essen',
        'perfect': 'gegessen'},
    'trinken': {
        'subject': 'Herr Feuerstein',
        'help': 'hat',
        'body': 'abends fünf Bier',
        'verb': 'trinken',
        'perfect': 'getrunken'},
    'anrufen': {
        'subject': 'Wir',
        'help': 'haben',
        'body': 'den Kundendienst',
        'verb': 'anrufen',
        'perfect': 'angerufen'},
    'aufstehen': {
        'subject': 'Herr Kolle',
        'help': 'ist',
        'body': 'um 6.00 Uhr ',
        'verb': 'aufstehen',
        'perfect': 'aufgestanden'},
    'anschließen': {
        'subject': 'Wir',
        'help': 'haben',
        'body': 'den Drucker',
        'verb': 'anschließen',
        'perfect': 'angeschlossen'},
    'abschließen': {
        'subject': 'Du',
        'help': 'hast',
        'body': 'das Studium bereits',
        'verb': 'abschließen',
        'perfect': 'abgeschlossen'},
    'ausschneiden': {
        'subject': 'Sie',
        'help': 'haben',
        'body': 'die Kästchen nicht',
        'verb': 'ausschneiden',
        'perfect': 'ausgeschnitten'},
    'abfahren': {
        'subject': 'Er',
        'help': 'ist',
        'body': 'den Parkplatz',
        'verb': 'abfahren',
        'perfect': 'abgefahren'},
    'ausgeben': {
        'subject': 'Wir',
        'help': 'haben',
        'body': 'unser ganzes Geld',
        'verb': 'ausgeben',
        'perfect': 'aufgegeben'},
    'einfügen': {
        'subject': 'Ich',
        'help': 'habe',
        'body': '',
        'verb': 'einfügen',
        'perfect': 'eingefügt'},
    'absagen': {
        'subject': 'Er',
        'help': 'hat',
        'body': 'seine Teilnahme',
        'verb': 'absagen',
        'perfect': 'abgesagt'},
}
